### ISSUE TITLE
0.5.0 issues, perhaps related to watchers

### ISSUE THREAD

**Issue by mattberther** [rogerc/file-stream-rotator#55]
I'm trying to update https://github.com/winstonjs/winston-daily-rotate-file to use `file-stream-rotater@0.5.0` and am encountering some issues. In an attempt to isolate the issue, I came up with the following script which eliminates the winston transport and demonstrates the issue using the file-stream-rotator directly.

``` javascript
var os = require('os');

var logStream = require('file-stream-rotator').getStream({
    filename: './logs/application-%DATE%.log',
    frequency: 'custom',
    size: '1k',
    max_logs: 4,
    end_stream: true
});

for (var i = 0; i < 10; i++) {
    logStream.write(randomString(1056) + os.eol);
}
```

The above code eventually errors with something similar to `Error: ENOENT: no such file or directory, watch 'logs/application-201909032108.log.9'`. Other times, the error says something like: `Error: EEXIST: file already exists, symlink './logs/application-201909032111.log.2' -> './logs/current.log'`.

In the event that I don't receive any errors, the script just hangs until I manually break it with CTRL-C.

Please let me know what else you need to help troubleshoot the issue.

**Comment by rogerc** [comment]
Hi @mattberther I've just pushed a new commit for version 0.5.2. Can you try that one out please?
I've changed to use lstatSync as if it changes too quickly the async version would cause the issues you were seeing.

**Comment by rogerc** [comment]
I'll push 0.5.2 to NPM later today. I'd appreciate if you could confirm all working within your Winston tests before I push it. Thanks.

**Comment by mattberther** [comment]
@rogerc Thanks. Those changes seem to fix the errors I was encountering. However, with `file-stream-rotator@0.5.2` the script pasted above still hangs until I break the execution with CTRL-C.

**Comment by mattberther** [comment]
I've also noticed that the cleanup seems to leave the original filename in place. In the above example, I have the following files in my folder after I break execution:

```
application-201909040749.log
application-201909040749.log.6
application-201909040749.log.7
application-201909040749.log.8
application-201909040749.log.9
```

I would not expect the original .log file to be there.

**Comment by rogerc** [comment]
Hi @mattberther 

I've pushed a new commit for release 0.5.3. I believe it fixes the new issues raised. The continuous execution was because of the file watcher remaining active. I've placed the file watcher behind a flag and force close the watcher when the stream closes.

Let me know if its OK now and I'll push the release to NPM

**Comment by rogerc** [comment]
Forgot to add that the issue with the logfile is because under the tests process.nextTick doesnt get called in time for the first log to be added to the auditFile. Before returning the stream, I am emitting the new event to make sure its written.

**Comment by mattberther** [comment]
Thanks @rogerc. This seems to have addressed these issues. Please let me know when you publish `file-stream-rotator@0.5.3`.

**Comment by rogerc** [comment]
I've just published 0.5.3.

Thanks for verifying release before publishing.
